// <auto-generated />
using System;
using Elia.Shared.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Elia.Shared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251204190145_RenamedRevisionToHistorical")]
    partial class RenamedRevisionToHistorical
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Elia.Shared.Models.Forecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DatasetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Horizon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHistoricalVersion")
                        .HasColumnType("boolean");

                    b.Property<int>("RawDataId")
                        .HasColumnType("integer");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("SolarMW")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ValidTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("VersionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("WindMW")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("RawDataId");

                    b.HasIndex("DatasetId", "Region", "ValidTime", "VersionTime");

                    b.ToTable("Forecasts");
                });

            modelBuilder.Entity("Elia.Shared.Models.RawData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RawData");
                });

            modelBuilder.Entity("Elia.Shared.Models.Forecast", b =>
                {
                    b.HasOne("Elia.Shared.Models.RawData", "RawData")
                        .WithMany()
                        .HasForeignKey("RawDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RawData");
                });
#pragma warning restore 612, 618
        }
    }
}
